### PR TITLE
Update to 2020 Scrum Guide with Markdown formatting

### PR DESCRIPTION
**Pull request by omeganot**
@peitor - Here's a version of the November 2020 Scrum Guide, formatted for Markdown support to match the headings, bullets, and text formatting of the official guide.

### CODE REVIEW

**Comment by peitor** [comment]
Thanks.

I am trying to make a commit that highlights the changes.
ATM i cannot see the differences nicely with this PR.

I will use your PR later to update to Markdown.
THANKS Rich!

**Comment by omeganot** [comment]
Ah, well I can help with that too.  I have a 2017 Markdown version ready to go.  I'll commit that, followed by the 2020 version.  I can submit those as two separate pull requests if it would be helpful for comparing changes and making the transition.  What do you think?

**Comment by peitor** [comment]
Yes please!!!!
For me its important to have the diff view at the end.

THANKS!!!

**Comment by omeganot** [comment]
Curious, I reverted my changes and checked in a 2017 Markdown version and noticed it updated this pull request with the additional commits.  I didn't fully expect that, because I'm still somewhat a newbie on pull requests.  =)

It seems that we could use this pull request for both the 2017 Markdown update and the 2020 Markdown update, and capture both as changes in your file, if you perform a standard merge commit.  This will, however, also include the original commit I made and the revert commit which brought me back to your original file.  If you'd like a cleaner commit history on the file, we should close this pull request, I'll re-fork the repo, and redo the commits.  What would you like to do?

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

**Comment by peitor** [comment]
As per our conversation lets do it again in a clean way.

THANKS!

**Pull request closed without merging**
